import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { Example } from "@/components/example";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.grid}>
          <Link href="/A" className={styles.card}>
            <h2 className={inter.className}>
              Page A <span>-&gt;</span>
            </h2>
            <p className={inter.className}>Translation bundle split page A</p>
          </Link>

          <Link href="/B" className={styles.card}>
            <h2 className={inter.className}>
              Page B <span>-&gt;</span>
            </h2>
            <p className={inter.className}>Translation bundle split page B</p>
          </Link>
          <Example />
        </div>
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  return {
    props: {},
  };
};
